travis:
  secure:
    BINSTAR_TOKEN: RG46IghqrXhfG7xnosGSpsn3jjCrNvCE5UrjotN/QCNgbyhpW4pmC5kXvAyjtybV9gu8viGQRffoNtQTqwh8M3OqOjcikccXt4xifvz/qPmLnTL+PfGA8NbKkjfu3ifowKcMJG5v7LO3m8rEYtJRGin5u/MAi/HTjLizG480oy6bOchnAOuUvdiI7+VmLN7GAG2OAMTE0NKl+UZmTIEXbmeMbJeDc8G+mCyxzJxNhJXl0pzp7Ddd32sHwB2I6El4IlUXui4xGi+xumhcn9bp+XVA3lFJntlqjRNyeQCvTh7H6nZPFat0aM2KraA+EtlvV3js0GSHVdazwhxCZBzgqmtS02t9THl/2Fmuv1q3gU0nFmV02iVCFF6+zYeZMltfChYDLLdRmV+J5qIFqPNrhg03wnJzq1m1e2BNvibi23yuct0vWzDZxQDNDSnk2DLHEPkpiQ2Q8m6Ny7niokUtCYAr1kQwzCKTuGrG7Ytf+c+lCslJLu7v0RTGHRz1JX1gHKhpg5JUs4XXNLMJypBjwSKeae0oI9hiJ1x/netsIemiRu+DiVyDMTp6XKyr5aAfIje+2P4AjfLI+4WCBgAaKZx1g4GwgLAYUYelEPued527bgIQOFdlHq68OOpz6EqzellkZ0eSNuzz7v7KkynT/OJP68lwvC0yvm0wTMd1CW4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
